services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - "8096:8096" # HTTP
      - "8920:8920" # HTTPS
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: unless-stopped
